baseURL = "http://jpp.sn/"
languageCode = "en-au"
title = "jpp.sn"
theme = "bookcase"

[permalinks]
  post = "/:year/:month/:title/"


[params]
  description = "Blog by Matthew Jeppesen"
  twitter_name = "matthewjeppesen"
  author = "Matthew Jeppesen"
